version: '3.8'

services:
  # ---------------------------
  # 1. NGINX GATEWAY
  # ---------------------------
  nginx:
    image: nginx:latest
    container_name: main_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount file từ thư mục gốc hiện tại vào container
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - ./uploads_data:/var/www/uploads:ro
    depends_on:
      - api
      - frontend
    networks:
      - app_network

  # ---------------------------
  # 2. BACKEND API
  # ---------------------------
  api:
    image: online_web_be
    container_name: IT4409_BE
    build:
      # Context: Trỏ vào thư mục chứa code Backend
      context: ./IT4409_BE
      # Dockerfile: Đường dẫn tương đối tính từ Context
      dockerfile: Api/Dockerfile 
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    volumes:
      - ./uploads_data:/app/wwwroot/uploads
    networks:
      - app_network

  # ---------------------------
  # 3. FRONTEND
  # ---------------------------
  frontend:
    build:
      # Context: Trỏ vào thư mục chứa code Frontend
      context: ./IT4409_FE
      dockerfile: Dockerfile
    container_name: frontend_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge